	<div class="page-header">
        <h1>Edição de Socio</h1>
    </div>
	<div class="row">
		<form action="" method="POST"/>
		  <div class="form-group">
			<label for="cnpj">CPF</label>
			<?=$this->form->getElement("cpf");?>			
		  </div>
		  <div class="form-group">
			<label for="nome_fantasia">Nome</label>
			<?=$this->form->getElement("nome");?>			
		  </div>
		  <div class="form-group">
			<label for="razao_social">E-mail</label>
			<?=$this->form->getElement("email");?>			
		  </div>
		  <div class="form-group">
			<label for="nome_fantasia">Empresas</label>
			<?=$this->form->getElement("empresas");?>			
		  </div>
		  <button type="submit" class="btn btn-default">Editar</button>
		</form>
	</div>	