      <div class="page-header">
        <h1>Socio - <?php echo $this->socio->getNome()?></h1>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>E-mail</th>
                <th>Empresas</th>
				
              </tr>
            </thead>
            <tbody>
			  <tr>
				<td><?php echo $this->socio->getId(); ?></td>
				<td><?php echo $this->socio->getNome(); ?></td>
				<td><?php echo $this->socio->getCpf(); ?></td>
				<td><?php echo $this->socio->getEmail(); ?></td>
				<td>
			<?php	if (count($this->socio->getEmpresas())>0) {
						foreach ($this->socio->getEmpresas() as $emp) {?>
							<p><?php echo $emp->getNomeFantasia(); ?></p>
			<?php		}
					}?>		
					
				</td>
			  </tr>
            </tbody>
          </table>
        </div>
      </div>

   