	<div class="page-header">
        <h1>Login</h1>
    </div>
	<div class="row">
		<form action="" method="POST" >
		  <div class="form-group">
			<label for="login">Login</label>
			<?=$this->form->getElement("login");?>			
		  </div>
		  <div class="form-group">
			<label for="senha">Senha</label>
			<?=$this->form->getElement("senha");?>			
		  </div>

		  <button type="submit" class="btn btn-default">Enviar</button>
		</form>
	</div>	