	<div class="page-header">
        <h1>Edição de Empresa</h1>
    </div>
	<div class="row">
		<form action="" method="POST"/>
		  <div class="form-group">
			<label for="cnpj">CNPJ</label>
			<?=$this->form->getElement("cnpj");?>			
		  </div>
		  <div class="form-group">
			<label for="razao_social">Razão Social</label>
			<?=$this->form->getElement("razao_social");?>			
		  </div>
		  <div class="form-group">
			<label for="nome_fantasia">Nome Fantasia</label>
			<?=$this->form->getElement("nome_fantasia");?>			
		  </div>
		  <div class="form-group">
			<label for="nome_fantasia">Socios</label>
			<?=$this->form->getElement("socios");?>			
		  </div>
		  <button type="submit" class="btn btn-default">Editar</button>
		</form>
	</div>	