      <div class="page-header">
        <h1>Empresa - <?php echo $this->empresa->getNomeFantasia(); ?></h1>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Nome Fantasia</th>
                <th>CNPJ</th>
                <th>Razão Social</th>
                <th>Socios</th>
				
              </tr>
            </thead>
            <tbody>
				  <tr>
					<td><?php echo $this->empresa->getId(); ?></td>
					<td><?php echo $this->empresa->getNomeFantasia(); ?></td>
					<td><?php echo $this->empresa->getCnpj(); ?></td>
					<td><?php echo $this->empresa->getRazaoSocial(); ?></td>
					<td>
			<?php	if (count($this->empresa->getSocios())>0) {
						foreach ($this->empresa->getSocios() as $soc) {?>
							<p><?php echo $soc->getNome()?></p>
			<?php		}
					}?>		
					</td>
				  </tr>
					
            </tbody>
          </table>
        </div>
      </div>

   